### PR TITLE
Add support for generic file types

### PR DESCRIPTION
**Pull request by matuszeg**
I wanted to have sync epub files and it was just easier to add support for any generic file type rather than hardcode in just epub and pdf. I updated the README how I thought it should look, but it's your project so feel free to change that to whatever you want. I also modified the Examples, but didn't really have a way to test them, so I figured you would do that. I am fairly certain they will work.

### CODE REVIEW

**Comment by matuszeg** [comment]
I would have tested this with other file formats like Mobi or something but i just got my Remarkable 2 yesterday and afaik the official apps can only handle pdf and epub. I know there are other apps people have made on github that can support Mobi and all sorts of things but it seems like Remarkable 2 support isnt there yet. So i cant really test if they worked until i dive into trying to get some other application running like Koreader or whatever

**Comment by bsdz** [comment]
Thanks for the PR. I'll take a closer look later. I don't think one can upload anything other than epub and pdf files to Remarkable. 

image

I think it's perhaps also best to make it non-optional. That would leave the examples unchanged.

**Comment by matuszeg** [comment]
I made "filters" optional just because i didn't want to break any existing examples or code that people have out in the wild if this were to get accepted into it.

So this morning I tried adding "mobi" to formats and it mostly does work. I think it is just blocked on the desktop frontend to only accept  pdf&epub. Because it accepted the files on the backend and I can see them listen in the desktop application, altho not really readable because it does not like the format. I did not the mobi files listed on the remarkable device interface, but when I connected through my computer with an sftp connection I did see the mobi files on the device. So it does work for more than just epub and pdf. You just need some other type of application to actually read the file. My hope is that Koreader or some of the other programs people have put on their devices will be able to grab these up easily and use them, but not sure because I dont have that on my device yet. I attached some screenshots of the desktop UI showing the mobi files and sftp client showing the mobi files on the device

image

image

**Comment by bsdz** [comment]
I just committed changes to support epub. Right now, I don't really want to add support for file types that might one day be read by other apps on the device. When this happens I'm happy to rethink. Thanks for your suggestions.

**Pull request closed without merging**
